/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VideoHeaderMapper */

#ifndef _Included_VideoHeaderMapper
#define _Included_VideoHeaderMapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VideoHeaderMapper
 * Method:    mpeg2decHeaderMain
 * Signature: ([BI[I)I
 */
JNIEXPORT jint JNICALL Java_VideoHeaderMapper_mpeg2decHeaderMain
  (JNIEnv *, jobject, jbyteArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
