/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WordCountMapper */

#ifndef _Included_WordCountMapper
#define _Included_WordCountMapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WordCountMapper
 * Method:    mpeg2decMain
 * Signature: ([BI[I[B[II[II)I
 */
JNIEXPORT jint JNICALL Java_WordCountMapper_mpeg2decMain
  (JNIEnv *, jobject, jbyteArray, jint, jintArray, jbyteArray, jintArray, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
