/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mpeg2decJNIcall */

#ifndef _Included_mpeg2decJNIcall
#define _Included_mpeg2decJNIcall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mpeg2decJNIcall
 * Method:    mpeg2decMain
 * Signature: ([BI[I[B[II[I)V
 */
JNIEXPORT void JNICALL Java_mpeg2decJNIcall_mpeg2decMain
  (JNIEnv *, jobject, jbyteArray, jint, jintArray, jbyteArray, jintArray, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
